### ISSUE TITLE
Cloud Talent Solution API: TenantOrProjectName cannot be resolved to a type

### ISSUE THREAD

**Issue by palmbeachjeff** [googleapis/java-talent#132]
Cloud Talent Solution API: TenantOrProjectName cannot be resolved to a type.  Using macOS Catalina 10.15.1 and working with Java 8, I have followed the Google Cloud Talent API Quick Guide here:

https://cloud.google.com/talent-solution/job-search/docs/quickstart-searching

After importing 'com.google.cloud:google-cloud-talent:0.36.1' (from here: https://cloud.google.com/talent-solution/job-search/docs/libraries#client-libraries-install-java) into my build.gradle file and running, the class 'TenantOrProjectName' from the documentation cannot resolve to a type in Eclipse.  

When looking through the api documentation, I didn't see a class with that name in it either.  I'm wondering if either the example is outdated or if I'm missing a library that isn't in the Java documentation.   

1.) Copy and paste searchJobs() method into Java program and 'TenantOrProjectName' can't be imported as they aren't recognized.  
```java
public static void searchJobs(String projectId, String tenantId, String query) {
		  try (JobServiceClient jobServiceClient = JobServiceClient.create()) {
		    // projectId = "Your Google Cloud Project ID";
		    // tenantId = "Your Tenant ID (using tenancy is optional)";
		    // query = "count(base_compensation, [bucket(12, 20)])";
		    **TenantOrProjectName** parent = TenantName.of(projectId, tenantId);
		    String domain = "www.example.com";
		    String sessionId = "Hashed session identifier";
		    String userId = "Hashed user identifier";
		    RequestMetadata requestMetadata =
		        RequestMetadata.newBuilder()
		            .setDomain(domain)
		            .setSessionId(sessionId)
		            .setUserId(userId)
		            .build();
		    HistogramQuery histogramQueriesElement =
		        HistogramQuery.newBuilder().setHistogramQuery(query).build();
		    List<HistogramQuery> histogramQueries = Arrays.asList(histogramQueriesElement);
		    SearchJobsRequest request =
		        SearchJobsRequest.newBuilder()
		            .setParent(parent.toString())
		            .setRequestMetadata(requestMetadata)
		            .addAllHistogramQueries(histogramQueries)
		            .build();
		    for (SearchJobsResponse.MatchingJob responseItem :
		        jobServiceClient.searchJobs(request).iterateAll()) {
		      System.out.printf("Job summary: %s\n", responseItem.getJobSummary());
		      System.out.printf("Job title snippet: %s\n", responseItem.getJobTitleSnippet());
		      Job job = responseItem.getJob();
		      System.out.printf("Job name: %s\n", job.getName());
		      System.out.printf("Job title: %s\n", job.getTitle());
		    }
		  } catch (Exception exception) {
		    System.err.println("Failed to create the client due to: " + exception);
		  }
		}
```

**Comment by chingor13** [comment]
Thanks for filing this. In version [0.36.0](https://github.com/googleapis/java-talent/releases/tag/v0.36.0), we introduced a breaking change to how resource names are generated/used. Unfortunately, the sample referenced is out of date (see https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2549). We will get this fixed and updated soon.

Rather than having an interface that represents either a project or a tenant resource, you should now explicitly choose either [`com.google.cloud.talent.v4beta1.ProjectName.of(project)`](https://googleapis.dev/java/google-cloud-talent/latest/com/google/cloud/talent/v4beta1/ProjectName.html#of-java.lang.String-) or [`com.google.cloud.talent.v4beta1.TenantName.of(project, tenant)`.](https://googleapis.dev/java/google-cloud-talent/latest/com/google/cloud/talent/v4beta1/TenantName.html#of-java.lang.String-java.lang.String-)

**Comment by MorthenDeveloper** [comment]
que es el TenantId?, y que se pasa como parámetro?
